# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EpankerCplusplus <- function(tk, tvalue, hband, delt) {
    .Call(`_sievePH_EpankerCplusplus`, tk, tvalue, hband, delt)
}

estpcomcplusplus <- function(tau, KK, N, NP, X, ZT, DELTA, WGHT, BETA0) {
    .Call(`_sievePH_estpcomcplusplus`, tau, KK, N, NP, X, ZT, DELTA, WGHT, BETA0)
}

estpipwcplusplus <- function(tau, KK, N, TBAND, NP, X, ZT, CENSOR, DELTA, WGHT, BETA0) {
    .Call(`_sievePH_estpipwcplusplus`, tau, KK, N, TBAND, NP, X, ZT, CENSOR, DELTA, WGHT, BETA0)
}

estpaugcplusplus <- function(tau, tstep, ntgrid, TBAND, KK, N, NP, X, ZT, CENSOR, DELTA, WGHT, DRHOipw, BETA0) {
    .Call(`_sievePH_estpaugcplusplus`, tau, tstep, ntgrid, TBAND, KK, N, NP, X, ZT, CENSOR, DELTA, WGHT, DRHOipw, BETA0)
}

GDIST2Ncplusplus <- function(nvgrid, iskip, zdev, KK, N, NP, X, ZT, betaofv, SigmaInv, S0N, S1N, tempaug, AsigInv) {
    .Call(`_sievePH_GDIST2Ncplusplus`, nvgrid, iskip, zdev, KK, N, NP, X, ZT, betaofv, SigmaInv, S0N, S1N, tempaug, AsigInv)
}

