# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EpankerCplusplus <- function(tk, tvalue, hband, delt) {
    .Call('_sievePH_EpankerCplusplus', PACKAGE = 'sievePH', tk, tvalue, hband, delt)
}

estpcomcplusplus <- function(tau, KK, N, NP, X, ZT, DELTA, WGHT, BETA0) {
    .Call('_sievePH_estpcomcplusplus', PACKAGE = 'sievePH', tau, KK, N, NP, X, ZT, DELTA, WGHT, BETA0)
}

estpipwcplusplus <- function(tau, KK, N, TBAND, NP, X, ZT, CENSOR, DELTA, WGHT, BETA0) {
    .Call('_sievePH_estpipwcplusplus', PACKAGE = 'sievePH', tau, KK, N, TBAND, NP, X, ZT, CENSOR, DELTA, WGHT, BETA0)
}

estpaugcplusplus <- function(tau, tstep, ntgrid, TBAND, KK, N, NP, X, ZT, CENSOR, DELTA, WGHT, DRHOipw, BETA0) {
    .Call('_sievePH_estpaugcplusplus', PACKAGE = 'sievePH', tau, tstep, ntgrid, TBAND, KK, N, NP, X, ZT, CENSOR, DELTA, WGHT, DRHOipw, BETA0)
}

GDIST2Ncplusplus <- function(nvgrid, iskip, zdev, KK, N, NP, X, ZT, betaofv, SigmaInv, S0N, S1N, tempaug, AsigInv) {
    .Call('_sievePH_GDIST2Ncplusplus', PACKAGE = 'sievePH', nvgrid, iskip, zdev, KK, N, NP, X, ZT, betaofv, SigmaInv, S0N, S1N, tempaug, AsigInv)
}

